name: Sync Catalog
on:
  repository_dispatch:
    types: [refresh_data]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run sync script
        run: node update.js
        env:
          YANDEX_API_URL: ${{ secrets.YANDEX_API_URL }}

      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add products.json
          git commit -m "Catalog update: $(date)" || echo "No changes to commit"
          git push